/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components

import 'notivue'

declare global {
  const $push: ReturnType<typeof import("notivue")["usePush"]>;
  interface Window {
    $push: ReturnType<typeof import("notivue")["usePush"]>;
  }
}

export {};
